import 'package:flutter/material.dart';

class AppIcons {
  static IconData getIconData(String name) {
    switch (name) {
      case 'favorite_rounded':
        return Icons.favorite_rounded;
      case 'child_care_rounded':
        return Icons.child_care_rounded;
      case 'psychology_rounded':
        return Icons.psychology_rounded;
      case 'medical_services_rounded':
        return Icons.medical_services_rounded;
      case 'health_and_safety_rounded':
        return Icons.health_and_safety_rounded;
      case 'family_restroom_rounded':
        return Icons.family_restroom_rounded;
      case 'home_rounded':
        return Icons.home_rounded;
      case 'shield_rounded':
        return Icons.shield_rounded;
      case 'done_all_rounded':
        return Icons.done_all_rounded;
      case 'phone_callback_rounded':
        return Icons.phone_callback_rounded;
      case 'widgets_rounded':
        return Icons.widgets_rounded;
      case 'payments_rounded':
        return Icons.payments_rounded;
      case 'question_answer_rounded':
        return Icons.question_answer_rounded;
      case 'bubble_chart_rounded':
        return Icons.bubble_chart_rounded;
      case 'alt_route_rounded':
        return Icons.alt_route_rounded;
      case 'bolt_rounded':
        return Icons.bolt_rounded;
      case 'admin_panel_settings_rounded':
        return Icons.admin_panel_settings_rounded;
      case 'face_rounded':
        return Icons.face_rounded;
      case 'business_center_rounded':
        return Icons.business_center_rounded;
      case 'corporate_fare_rounded':
        return Icons.corporate_fare_rounded;
      case 'code_rounded':
        return Icons.code_rounded;
      case 'fingerprint_rounded':
        return Icons.fingerprint_rounded;
      case 'send_rounded':
        return Icons.send_rounded;
      case 'star_rounded':
        return Icons.star_rounded;
      case 'trending_up_rounded':
        return Icons.trending_up_rounded;
      case 'cloud_queue_rounded':
        return Icons.cloud_queue_rounded;
      case 'lightbulb_rounded':
        return Icons.lightbulb_rounded;
      case 'calendar_month_rounded':
        return Icons.calendar_month_rounded;
      case 'support_agent_rounded':
        return Icons.support_agent_rounded;
      case 'verified_user_rounded':
        return Icons.verified_user_rounded;
      case 'email_rounded':
        return Icons.email_rounded;
      case 'phone_rounded':
        return Icons.phone_rounded;
      case 'info_rounded':
        return Icons.info_rounded;
      case 'settings_suggest_rounded':
        return Icons.settings_suggest_rounded;
      case 'people_alt_rounded':
        return Icons.people_alt_rounded;
      case 'verified_rounded':
        return Icons.verified_rounded;
      case 'public_rounded':
        return Icons.public_rounded;
      case 'bar_chart_rounded':
        return Icons.bar_chart_rounded;
      case 'trending_down_rounded':
        return Icons.trending_down_rounded;
      case 'rocket_launch_rounded':
        return Icons.rocket_launch_rounded;
      case 'workspace_premium_rounded':
        return Icons.workspace_premium_rounded;
      case 'monetization_on_rounded':
        return Icons.monetization_on_rounded;
      case 'groups_rounded':
        return Icons.groups_rounded;
      case 'handshake_rounded':
        return Icons.handshake_rounded;
      case 'inventory_2_rounded':
        return Icons.inventory_2_rounded;
      case 'check_circle_rounded':
        return Icons.check_circle_rounded;
      case 'location_on_rounded':
        return Icons.location_on_rounded;
      case 'article_rounded':
        return Icons.article_rounded;
      case 'storefront_rounded':
        return Icons.storefront_rounded;
      case 'mark_email_read_rounded':
        return Icons.mark_email_read_rounded;
      case 'campaign_rounded':
        return Icons.campaign_rounded;
      case 'people_rounded':
        return Icons.people_rounded;
      case 'help_outline_rounded':
        return Icons.help_outline_rounded;
      case 'speed_rounded':
        return Icons.speed_rounded;
      case 'security_rounded':
        return Icons.security_rounded;
      case 'integration_instructions_rounded':
        return Icons.integration_instructions_rounded;
      case 'analytics_rounded':
        return Icons.analytics_rounded;
      case 'person_add_alt_1_rounded':
        return Icons.person_add_alt_1_rounded;
      case 'tune_rounded':
        return Icons.tune_rounded;
      case 'link_rounded':
        return Icons.link_rounded;
      case 'brush_rounded':
        return Icons.brush_rounded;
      case 'dashboard_rounded':
        return Icons.dashboard_rounded;
      case 'chat_rounded':
        return Icons.chat_rounded;
      default:
        return Icons.star_rounded;
    }
  }
}